name: Example workflow for Python using Snyk

on: push

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Authenticate Snyk
        env: SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        uses: snyk/actions/python-3.8@master

        with:
          command: auth ${{ secrets.SNYK_TOKEN }}
          
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env: SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        env: SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          sarif_file: snyk.sarif
